# Dockerfile.streamlit
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el nuevo archivo
COPY frontend.py .

# Expone el puerto (Railway usará la variable PORT)
EXPOSE 8080

# Ejecuta el nuevo archivo
CMD ["sh", "-c", "streamlit run frontend.py --server.port=${PORT:-8080} --server.address=0.0.0.0"]
